'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClaimSampleBatch
    Public Property ClaimSampleBatchID As Integer
    Public Property ClaimedAssignedReviewerID As Integer
    Public Property UserID As Integer

    Public Property ClaimSelectSamplePercent As Double
    Public Property ClaimDeltaPercent As Double?
    Public Property IsCalcDone As Boolean
    Public Property __UPDATE__ as Boolean

    Public Sub _updateClone(ByRef dr As DataRow)
        __UPDATE__ = true
        _clone(dr)
    End Sub
    Public Sub _clone(ByRef dr As DataRow)
        ClaimSampleBatchID = dr("ClaimSampleBatchID")
        ClaimSelectSamplePercent = dr("ClaimSelectSamplePercent")
        ClaimDeltaPercent = dr("ClaimDeltaPercent")
        IsCalcDone = dr("IsCalcDone")
    End Sub

End Class
