'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSamplePercent
    Public Property ID As Integer
    Public Property MinValue As Decimal
    Public Property  MaxValue As Decimal
    Public Property Percent As Double

    Public Property Type As String
    

End Class
