'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSamplePercent
    Public Property ID As Integer

    Public Property TypePrivate As String
    Public Property MinValuePrivate As Decimal
    Public Property MaxValuePrivate As Decimal
    Public Property PercentPrivate As Double


    Public Property TypePublic As String
    Public Property MinValuePublic As Decimal
    Public Property MaxValuePublic As Decimal
    Public Property PercentPublic As Double


End Class
